<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="../../static/style.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>A pickle of a Python ValueError - alligator's blog</title>
</head>
<body>
  <header>
    
<h1>
  <a href="../">alligator's blog</a>
</h1>

  </header>
  <div class="page">
    
<h2>A pickle of a Python ValueError</h2>
Aug 23, 2023
<div class="blog-post">

  

  <p>I have a custom feed aggregator written in Python. To be <a href="http://rachelbythebay.com/w/2023/01/18/http/">well behaved</a>, it keeps a cache of previous feeds it's fetched. It <a href="https://docs.python.org/3/library/pickle.html#pickle.load">unpickles</a> the cache from a file after it starts, and <a href="https://docs.python.org/3/library/pickle.html#pickle.dump">pickles</a> it to a file before it exits.</p>
<p>Every few months it would throw this exception while it's pickling the cache to a file:</p>
<pre><code>Traceback (most recent call last):
  File "rss.py", line 404, in &lt;module&gt;
    pickle.dump(cache, f)
ValueError: I/O operation on closed file.
</code></pre>
<p>It would only happen once. If I ran it again, no exception.</p>
<p>This is the <code>pickle.dump</code> call on that line:</p>
<div class="hll"><pre><span></span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">cache_file</span><span class="p">,</span> <span class="s1">&#39;wb&#39;</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
  <span class="n">pickle</span><span class="o">.</span><span class="n">dump</span><span class="p">(</span><span class="n">cache</span><span class="p">,</span> <span class="n">f</span><span class="p">)</span>
</pre></div>
<p><em>How can the file be closed if I opened it on the line before?</em></p>
<p>Turns out, it's not. It's a different file. Here's how I figured that out.</p>
<h2 id="tl-dr-what-was-the-problem">tl;dr, what was the problem?</h2><p>The <code>cache</code> object being pickled contained, deep in it's hierarchy, a file-like object that was closed. That was the source of the exception.</p>
<hr>
<p>First I had to find a reproducible case and... I just waited. It took about six months until it happened reproducibly. Once I had that, I started debugging.</p>
<p>Debugging was frustrating at first. Every exception pointed to the <code>pickle.dump</code> call, and I couldn't step into it because it's a native function written in C. Fortunately there's a pure Python version of pickle. It's only used if the native one can't be loaded, but its functions are still there with underscore prefixes.</p>
<p>Changing the call to this allowed me to step into pickle:</p>
<div class="hll"><pre><span></span><span class="n">pickle</span><span class="o">.</span><span class="n">_dump</span><span class="p">(</span><span class="n">cache</span><span class="p">,</span> <span class="n">f</span><span class="p">)</span>
</pre></div>
<p>The object being pickled when the exception was thrown looked interesting:</p>
<pre><code>&lt;_io.BytesIO object at 0x0000015373D15A80&gt;
</code></pre>
<p>That's a <a href="https://docs.python.org/3/glossary.html#term-file-object">file-like object</a>. I wonder what it's <code>closed</code> property is?</p>
<pre><code>p obj.closed
True
</code></pre>
<p>Hello closed "file". Where did you come from?</p>
<p>Pickle is recursive, so I could look through the stack and see the object hierarchy. The <code>io.BytesIO</code> object is inside a <a href="https://docs.python.org/3/library/xml.sax.html#xml.sax.SAXParseException"><code>SAXParseException</code></a>. Where did <em>that</em> come from?</p>
<aside>
<p>Feedparser calls badly-formed feeds "bozos" and these exceptions are "bozo exceptions", which is pretty wonderful.</p>
</aside><p>My feed aggregator uses <a href="https://github.com/kurtmckee/feedparser">feedparser</a>. When that fails to parse a feed, it returns an object containing the exception. In my repro case, a feed would always fail to parse and return a <code>SAXParseException</code>.</p>
<!-- obj.bozo_exception._locator._source._InputSource__bytefile -->

<!-- - The exception contained the `XMLReader` that threw it -->
<!-- - which contained an `InputSource` -->
<!-- - which contained a `__bytefile` property -->
<!-- - which contained the closed `io.BytesIO` above -->

<!--
- `feedparser.util.FeedParserDict.bozo_exception`
  - `xml.sax._exceptions.SAXParseException._locator`
      - `xml.sax.expatreader.ExpatParser._source`
          - `xml.sax.xmlreader.InputSource._InputSource__bytefile`
              - `io.BytesIO`
-->


<p>The aggregator then put this object into the cache, <em>without checking if it contains an exception</em>. Later on, pickle tries to serialize this exception and throws the ValueError.</p>
<p>But, why does the closed <code>io.BytesIO</code> object throw that exception when it's pickled? For that, we need to look at its <a href="https://github.com/python/cpython/blob/1700d34d314f5304a7a75363bda295a8c15c371f/Modules/_io/bytesio.c">source</a>.</p>
<p>An object can override <code>__getstate__</code> to <a href="https://docs.python.org/3/library/pickle.html#object.__getstate__">change how it's pickled</a>. <code>io.BytesIO</code> <a href="https://github.com/python/cpython/blob/1700d34d314f5304a7a75363bda295a8c15c371f/Modules/_io/bytesio.c#L786">does this</a>, and will <a href="https://github.com/python/cpython/blob/1700d34d314f5304a7a75363bda295a8c15c371f/Modules/_io/bytesio.c#L38">throw a ValueError</a> if it's internal buffer is closed (i.e. null). I'm not sure when this particular <code>io.BytesIO</code> gets closed, but it's wrapped around the response body of the HTTP request that fetched the feed. That itself is a file-like object, and has probably long-since been closed.</p>
<p>So, the problem is that feedparser returns an object, that contains a <code>SAXParseException</code>, that contains an <code>io.BytesIO</code> object, that is closed, and my feed aggregator tries to pickle it.</p>
<h2 id="the-fix">The fix</h2><p>I fixed this in two ways:</p>
<ol>
<li>Don't populate the cache if the feed failed to parse</li>
<li>Don't pickle the whole result from feedparser, just pickle the text content of the feed</li>
</ol>
<p>If you get a weird ValueError on a <code>pickle.dump</code> call, check what you're pickling.</p>

</div>
<p>
  <a href="../">blog index</a>
</p>

  </div>
  <script data-goatcounter="https://alligator.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
</body>
</html>
